#!/bin/bash
#
# Wrapper around the spack environment that defines some useful commands.
#
# Activate the environment by sourcing this file with
#     . activate_h3env
# 
# Run 'help_h3env' with the environment activated to see the available commands

# Record top-level dir
REPO_ROOT=$( cd -- "$(realpath $( dirname -- "${BASH_SOURCE[0]}" ))" &> /dev/null && pwd )

# Save shell options
OLD_SHOPTS="$(set +o)"

#======================= Convenience aliases/functions ========================

# Creates a link to the specified target (first argument) with the specified
# name (second argument), unless a link with that target and name already
# exists. It will overwrite links to different targets. Also print a message
# saying what it is doing.
_create-link() {
    target="$1"
    link="$2"
    if ! [[ -L "$link" && $(readlink "$link") == "$target" ]]
    then
        echo "    Linking $(realpath -s --relative-to="$REPO_ROOT" "$link") => $target"
        rm -f "$link" > /dev/null
        ln -s "$target" "$link"
    fi
}

# Remove convenience aliases/function definitions and deactivate the env
deactivate_h3env() {

    unset -f _create-link
    unset -f deactivate_h3env
    unalias help_h3env
    unset -f in_h3env
    unset REPO_ROOT
    unset -f usage_h3env

    spack env deactivate
}

# Run commands in the build environment
h3spec="hermes-3%gcc"
in_h3env() {
  if [ $# -eq 0 ]; then
    usage_h3env
    return
  fi
  cmd="spack build-env ${h3spec} $@"
  echo $cmd
  eval $cmd
}

# Print help/usage info
usage_h3env() {
    echo " . activate_h3env  : Activate the environment"
    echo " deactivate_h3env  : Deactivate the environment"
    echo " help_h3env        : Show this message"
    echo ' in_h3env [args]   : Run a command in the build environment: (e.g. export h3_build="./builds/my_build" && in_h3env cmake -B "$h3_build" && in_h3env cmake --build "$h3_build" -j8)'
}
alias help_h3env=usage_h3env

#============================== Run on activate ===============================

# Check that spack has been set up
spacktivate_cmd="spacktivate"
if ! command -v "$spacktivate_cmd" &> /dev/null
  then
    echo "The $spacktivate_cmd alias doesn't seem to be defined. Have you installed spack and sourced \$SPACK_ROOT/share/spack/setup-env.sh?"
    return 1
fi

# Check that the BOUT-spack submodule has been cloned
sm_name="BOUT-spack"
bout_spack_relpath="${sm_name}/spack_repo/bout"
repo_yaml="${REPO_ROOT}/external/${bout_spack_relpath}/repo.yaml"
if [ ! -f "$repo_yaml" ]
  then
    echo "$repo_yaml doesn't exist. Has the ${sm_name} git submodule been initialised?"
    echo "  (git submodule update --init)"
    return 
fi

# Activate the environment and load the view
spacktivate . -p -v gcc