#!/usr/bin/env python3
from boututils.run_wrapper import shell, launch_safe, getmpirun
import numpy as np
import matplotlib.pyplot as plt
import shutil
import zipfile
import hashlib
import os
from pathlib import Path
import urllib.request
import xhermes
from time import time

t0 = time()

"""
This test reconstructs neutra target density and energy sources due to recycling 
and compares them to code output. It uses the same file as 2D-production.

It mirrors the code in recycling.cxx. It's written in a way to allow easy debugging
of the recycling calculation for development reasons.
"""

verbose = True
plot = False
debug = False  # Do not download files or run test
rtol = 1e-6
atol = 1e-8

### Setup
this_dir = Path(__file__).parent
data_dir = this_dir / "data"
hermes_exec = this_dir.parent.parent.parent / "hermes-3"
output_path = data_dir / "BOUT.dmp.*.nc"

zipfile_path = this_dir / "test-2D-recycling.zip"
url = "https://zenodo.org/records/18696440/files/test-2D-production-2026-02-19.zip"
expected_hash = "4472d27031a6fcedd30e11360814a66c075f8c14442df745e4e9d80a0dbd87f3"
expected_filenames = [
    "BOUT.restart.0.nc",
    "BOUT.restart.1.nc",
    "BOUT.restart.2.nc",
    "BOUT.restart.3.nc",
    "BOUT.restart.4.nc",
    "BOUT.restart.5.nc",
    "BOUT.restart.6.nc",
    "BOUT.restart.7.nc",
    "BOUT.restart.8.nc",
    "BOUT.restart.9.nc",
    "grid_test2_allpump.nc",
]


### Download files
if not debug:
    tmp_path = zipfile_path.with_name(zipfile_path.name + ".tmp")

    with urllib.request.urlopen(url, timeout=60) as response:
        if response.status != 200:
            raise RuntimeError(
                f"2D-recycling test: download failed - HTTP {response.status}"
            )

        # Copy bits of the file from response to a temp file
        # This ensures no partial files are left if the download fails
        with open(tmp_path, "wb") as out_file:
            shutil.copyfileobj(response, out_file)

    t_download = time()
    if verbose:
        print(f"2D-Recycling test: download took {t_download - t0:.2f} seconds")

    # Rename temp file with the correct name
    tmp_path.replace(zipfile_path)

    with zipfile.ZipFile(zipfile_path, "r") as zf:
        zip_contents = set(zf.namelist())
        try:
            # Extract only expected grids
            for filename in expected_filenames:
                if filename in zip_contents:
                    zf.extract(filename, path=this_dir)

        except Exception as e:
            print("2D-recycling test: extracting test grids failed:", e)

    # Check hash
    with open(zipfile_path, "rb") as f:
        file_hash = hashlib.sha256(f.read()).hexdigest()
        # print(file_hash)

    if file_hash != expected_hash:
        raise RuntimeError(
            "2D-recycling test: downloaded zip file hash does not match expected value"
        )

    t_extract = time()
    if verbose:
        print(
            f"2D-Recycling test: zip extraction took {t_extract - t_download:.2f} seconds"
        )

    ## Run test
    if not Path("hermes-3").is_file():
        shell("ln -s ../../../hermes-3 hermes-3")

    runcmd = getmpirun().split(" ")[0] + " -np"

    # Allow oversubscription for OpenMPI via env var (silently ignored by MPICH,
    # which does not enforce slot limits and does not support --oversubscribe)
    os.environ["OMPI_MCA_rmaps_base_oversubscribe"] = "yes"

    s, out = launch_safe("./hermes-3 -d data", runcmd=runcmd, nproc=10, pipe=True)

    if s != 0:
        print(" => 2D-recycling test failed: ")
        print(out)
        exit(1)

    t_run = time()
    if verbose:
        print(f"2D-Recycling test: simulation took {t_run - t_extract:.2f}")

##########################################################################
# Load case and perform test
##########################################################################
# The case is read without unnormalising to make debugging easier.
# The sources of density and energy due to recycling and pumping on both
# the outer lower and outer upper target are reproduced in Python and
# compared to the simulation.
##########################################################################

### Load case
ds = xhermes.open_hermesdataset(
    datapath=output_path,
    inputfilepath=this_dir / "data" / "BOUT.inp",
    gridfilepath=this_dir / "grid_test2_allpump.nc",
    keep_yboundaries=True,
    keep_xboundaries=True,
    geometry="toroidal",
    unnormalise=False,
).isel(t=-1)

ds = ds.hermes.extract_2d_tokamak_geometry()

ds = ds.load()

t_load = time()
if verbose:
    print(f"2D-Recycling test: loading results took {t_load - t_run:.2f} seconds")

if "t" in ds.sizes:
    ds = ds.isel(t=-1)
m = ds.metadata

### Extract data
# Options
options = ds.options
# target_multiplier = options["d+"]["target_recycle_multiplier"]
target_multiplier = options["d+"]["pump_recycle_multiplier"]  # pump overrides
target_energy = options["d+"]["target_recycle_energy"] / m["Tnorm"]
target_fast_recycle_fraction = options["d+"]["target_fast_recycle_fraction"]
target_fast_recycle_energy_factor = options["d+"]["target_fast_recycle_energy_factor"]
gamma_i = options["sheath_boundary_simple"]["gamma_i"]

if "density_floor" in options["d+"]:
    density_floor = options["d+"]["density_floor"]
else:
    density_floor = 1e-7

if "pressure_floor" in options["d+"]:
    pressure_floor = options["d+"]["pressure_floor"]
else:
    pressure_floor = density_floor * (1 / m["Tnorm"])

# Constants
Mi = 2

# Geometry and physics
params = [
    "J",
    "g_22",
    "dx",
    "dy",
    "dz",
    "dv",
    "Ne",
    "Nd",
    "Nd+",
    "Vd+",
    "Pd",
    "Td",
    "Td+",
]
d = {}
for param in params:
    d[param] = ds[param].values


### Functions
def floor(value, min):
    return np.maximum(value, min)


def at_sheath(f, i, g):
    """
    Linear interpolation between final and guard cell.
    f = field, i = final cell slice, g = guard cell slice.
    """
    return 0.5 * (f[i] + f[g])


def reconstruct_target_recycle(name):
    """
    Reconstructs neutral density and energy sources due to target recycling,
    as well as neutral density and energy sources due to pumping.

    Parameters
    ----------
    name : str
        Target region name, either "outer_lower_target" or "outer_upper_target".

    Returns
    -------
    reg : xarray.Dataset
        The dataset of the target region (final domain cell row, excluding guard
        cells and the final domain cells on each end to avoid SOL/PFR recycling effects).
    target_recycle_density_source : numpy.ndarray
        Calculated density source due to target recycling.
    target_recycle_energy_source : numpy.ndarray
        Calculated energy source due to target recycling.
    target_pump_density_source : numpy.ndarray
        Calculated density source due to target pumping.
    target_pump_energy_source : numpy.ndarray
        Calculated energy source due to target pumping.
    debug : numpy.ndarray
        This allows you to take any intermediate calculation value and output it for debugging
        purposes, such as comparing it to an intermediate value in Hermes-3.

    """
    ### Indexing
    xslice = slice(3, -3)
    i_index = xhermes.slice_poloidal(ds, name)

    # i = final domain cell
    # g = guard cell
    # s = second to final cell
    if name == "outer_lower_target":
        g_index = i_index + 1
        s_index = i_index - 1
    elif name == "outer_upper_target":
        g_index = i_index - 1
        s_index = i_index + 1

    i = (xslice, i_index)
    g = (xslice, g_index)
    s = (xslice, s_index)
    reg = ds.hermes.select_region(name).isel(x=slice(1, -1))

    ### Calculate sheath values
    sheath = {}
    for param in params:
        sheath[param] = at_sheath(d[param], i, g)

    daparsheath = (
        (d["J"][i] + d["J"][g])
        / (np.sqrt(d["g_22"][i]) + np.sqrt(d["g_22"][g]))
        * 0.5
        * (d["dx"][i] + d["dx"][g])
        * 0.5
        * (d["dz"][i] + d["dz"][g])
    )

    ### Floors
    Nnlim = floor(d["Nd"], density_floor)
    Pnlim = floor(d["Pd"], pressure_floor)
    Tnlim = Pnlim / Nnlim

    ### Calculate density source
    flux = abs(sheath["Ne"] * sheath["Vd+"])
    recycle_particle_flow = target_multiplier * flux * daparsheath

    volume = d["dv"][i]

    ### Calculate energy source
    sheath_ion_heat_flow = (
        abs(gamma_i * sheath["Nd+"] * sheath["Td+"] * sheath["Vd+"])
        * daparsheath
        / volume
    )

    recycle_energy_flow = (
        sheath_ion_heat_flow
        * target_multiplier
        * target_fast_recycle_energy_factor
        * target_fast_recycle_fraction
        + recycle_particle_flow * (1 - target_fast_recycle_fraction) * target_energy
    )

    nnguard = d["Nd"][i] ** 2 / Nnlim[s]
    tnguard = d["Td"][i] ** 2 / Tnlim[s]

    nnsheath = 0.5 * (d["Nd"][i] + nnguard)
    tnsheath = 0.5 * (d["Td"][i] + tnguard)
    v_th = 0.25 * np.sqrt(8 * tnsheath / (np.pi * Mi))

    pump_neutral_particle_flow = v_th * nnsheath * daparsheath
    pump_neutral_particle_sink = (
        pump_neutral_particle_flow / volume * (1 - target_multiplier)
    )

    pump_neutral_energy_flow = 2 * tnsheath * v_th * nnsheath * daparsheath
    pump_neutral_energy_sink = (
        pump_neutral_energy_flow / volume * (1 - target_multiplier)
    )

    target_recycle_density_source = recycle_particle_flow / volume
    target_recycle_energy_source = recycle_energy_flow / volume

    target_pump_density_source = -pump_neutral_particle_sink
    target_pump_energy_source = -pump_neutral_energy_sink

    # Change this to whatever you want to debug.
    debug = d["Td"][s]

    return (
        reg,
        target_recycle_density_source,
        target_recycle_energy_source,
        target_pump_density_source,
        target_pump_energy_source,
        debug,
    )


def plot_result(ax, xplot, sim_result, calc_result, title):
    ax.plot(xplot, sim_result, label="Simulation Result", lw=1, ms=7, marker="o", c="k")
    ax.plot(xplot, calc_result, label="Calc Result", lw=1, ms=7, marker="o", c="r")
    ax.set_ylabel("Value")
    ax2 = ax.twinx()
    ax2.plot(xplot, calc_result / sim_result, lw=1, c="blue")
    ax2.set_ylabel("Calc/sim ratio", color="blue")
    ax.set_title(title, fontsize="small")
    ax.legend(fontsize="x-small")


# -------------------------------------------------------------------------------#
### Test
# -------------------------------------------------------------------------------#

### Calculate data
reg = {}
target_recycle_density_source = {}
target_recycle_energy_source = {}
target_pump_density_source = {}
target_pump_energy_source = {}

expected_recycle_density_source = {}
expected_recycle_energy_source = {}
expected_pump_density_source = {}
expected_pump_energy_source = {}

debug = {}

for side in ["upper", "lower"]:
    (
        reg[side],
        target_recycle_density_source[side],
        target_recycle_energy_source[side],
        target_pump_density_source[side],
        target_pump_energy_source[side],
        debug[side],
    ) = reconstruct_target_recycle(f"outer_{side}_target")

    expected_recycle_density_source[side] = reg[side]["Sd_target_recycle"]
    expected_recycle_energy_source[side] = reg[side]["Ed_target_recycle"]
    expected_pump_density_source[side] = reg[side]["Sd_pump"]
    expected_pump_energy_source[side] = reg[side]["Ed_pump"]


### Plotting
if plot:
    fig, axes = plt.subplots(2, 4, figsize=(12, 7), dpi=100)

    for i, side in enumerate(["lower", "upper"]):
        plot_result(
            axes[i, 0],
            reg[side]["x"].values,
            sim_result=expected_recycle_density_source[side],
            calc_result=target_recycle_density_source[side],
            title=f"{side.capitalize()} target recycle\ndensity source",
        )

        plot_result(
            axes[i, 1],
            reg[side]["x"].values,
            sim_result=expected_recycle_energy_source[side],
            calc_result=target_recycle_energy_source[side],
            title=f"{side.capitalize()} target recycle\nenergy source",
        )

        plot_result(
            axes[i, 2],
            reg[side]["x"].values,
            sim_result=expected_pump_density_source[side],
            calc_result=target_pump_density_source[side],
            title=f"{side.capitalize()} target pump\ndensity source",
        )

        plot_result(
            axes[i, 3],
            reg[side]["x"].values,
            sim_result=expected_pump_energy_source[side],
            calc_result=target_pump_energy_source[side],
            title=f"{side.capitalize()} target pump\nenergy source",
        )

    fig.tight_layout()
    fig.savefig("target_recycle_pump_test.png", bbox_inches="tight")


### Asserts
for side in ["upper", "lower"]:
    np.testing.assert_allclose(
        target_recycle_density_source[side],
        expected_recycle_density_source[side].values,
        rtol=rtol,
        atol=atol,
        err_msg=f"{side} target recycle density source mismatch",
    )
    np.testing.assert_allclose(
        target_recycle_energy_source[side],
        expected_recycle_energy_source[side].values,
        rtol=rtol,
        atol=atol,
        err_msg=f"{side} target recycle energy source mismatch",
    )
    np.testing.assert_allclose(
        target_pump_density_source[side],
        expected_pump_density_source[side].values,
        rtol=rtol,
        atol=atol,
        err_msg=f"{side} target pump density source mismatch",
    )
    np.testing.assert_allclose(
        target_pump_energy_source[side],
        expected_pump_energy_source[side].values,
        rtol=rtol,
        atol=atol,
        err_msg=f"{side} target pump energy source mismatch",
    )

t_final = time()
print(f"2D-Recycling test: Passed in {t_final - t0:.2f} seconds")
